function corner = FAST_12(img, threshold_percentage)
%FAST_12  Features from Accelerated Segment Test (12-contiguous test).
%
%   corner = FAST_12(img, threshold_percentage)
%
%   Implements the FAST corner detector of Rosten & Drummond (ECCV 2006)
%   using a circle of radius 3 (16 surrounding pixels). A candidate pixel
%   is accepted when at least 12 contiguous neighbours are all brighter
%   (or all darker) than the centre by more than the local threshold.
%
%   Inputs
%     img                   - grayscale image (uint8 / double)
%     threshold_percentage  - threshold as a fraction of centre intensity
%                             (e.g. 0.3 → 30 % of I(x,y))
%
%   Output
%     corner - N-by-2 matrix of [row, col] corner coordinates
%
%   Used in the paper as the textured-region keypoint detector that feeds
%   the BRIEF descriptor branch of the copy-move pipeline.
%
%   See also FAST_non_max, BRIEF_descriptor.

corners = zeros(size(img,1), size(img,2));

% Scan the image interior (border of 3 px is required for the FAST circle).
for i = 4 : (size(img,1) - 3)
    for j = 4 : (size(img,2) - 3)
       threshold = threshold_percentage * img(i,j);
       I_pos = img(i,j) - threshold;   % darker-than-centre bound
       I_neg = img(i,j) + threshold;   % brighter-than-centre bound

       % ---- Accelerated rejection test on the four cardinal pixels ----
       % Only continue if opposite pairs already look promising.
       if I_pos > img(i-3,j) || I_neg < img(i-3,j)
           if I_pos > img(i,j+3) || I_neg < img(i,j+3)
               if I_pos > img(i+3,j) || I_neg < img(i+3,j)
                   % Contiguous arc starting near the top of the circle.
                   if (I_pos>img(i-3,j-1)&&...
                           I_pos>img(i-3,j+1)&&...
                           I_pos>img(i-2,j+2)&&...
                           I_pos>img(i-1,j+3)&&...
                           I_pos>img(i+1,j+3)&&...
                           I_pos>img(i+2,j+2)&&...
                           I_pos>img(i+3,j+1)&&...
                           I_pos>img(i+3,j-1))||...
                           (I_neg<img(i-3,j-1)&&...
                           I_neg<img(i-3,j+1)&&...
                           I_neg<img(i-2,j+2)&&...
                           I_neg<img(i-1,j+3)&&...
                           I_neg<img(i+1,j+3)&&...
                           I_neg<img(i+2,j+2)&&...
                           I_neg<img(i+3,j+1)&&...
                           I_neg<img(i+3,j-1))
                       corners(i,j) = 1;
                   end
               end
           end
       elseif I_pos > img(i,j+3) || I_neg < img(i,j+3)
           if I_pos > img(i+3,j) || I_neg < img(i+3,j)
               if I_pos > img(i,j-3) || I_neg < img(i,j-3)
                   % Contiguous arc starting near the right of the circle.
                   if (I_pos>img(i-1,j+3)&&...
                           I_pos>img(i+1,j+3)&&...
                           I_pos>img(i+2,j+2)&&...
                           I_pos>img(i+3,j+1)&&...
                           I_pos>img(i+3,j-1)&&...
                           I_pos>img(i+2,j-2)&&...
                           I_pos>img(i+1,j-3)&&...
                           I_pos>img(i-1,j-3))||...
                           (I_neg<img(i-1,j+3)&&...
                           I_neg<img(i+1,j+3)&&...
                           I_neg<img(i+2,j+2)&&...
                           I_neg<img(i+3,j+1)&&...
                           I_neg<img(i+3,j-1)&&...
                           I_neg<img(i+2,j-2)&&...
                           I_neg<img(i+1,j-3)&&...
                           I_neg<img(i-1,j-3))
                       corners(i,j) = 1;
                   end
               end
           end
       elseif I_pos > img(i+3,j) || I_neg < img(i+3,j)
           if I_pos > img(i,j-3) || I_neg < img(i,j-3)
               if I_pos > img(i-3,j) || I_neg < img(i-3,j)
                   % Contiguous arc starting near the bottom of the circle.
                   if (I_pos>img(i+3,j+1)&&...
                           I_pos>img(i+3,j-1)&&...
                           I_pos>img(i+2,j-2)&&...
                           I_pos>img(i+1,j-3)&&...
                           I_pos>img(i-1,j-3)&&...
                           I_pos>img(i-2,j-2)&&...
                           I_pos>img(i-3,j-1)&&...
                           I_pos>img(i-3,j+1))||...
                           (I_neg<img(i+3,j+1)&&...
                           I_neg<img(i+3,j-1)&&...
                           I_neg<img(i+2,j-2)&&...
                           I_neg<img(i+1,j-3)&&...
                           I_neg<img(i-1,j-3)&&...
                           I_neg<img(i-2,j-2)&&...
                           I_neg<img(i-3,j-1)&&...
                           I_neg<img(i-3,j+1))
                       corners(i,j) = 1;
                   end
               end
           end
       elseif I_pos > img(i,j-3) || I_neg < img(i,j-3)
           if I_pos > img(i-3,j) || I_neg < img(i-3,j)
               if I_pos > img(i,j+3) || I_neg < img(i,j+3)
                   % Contiguous arc starting near the left of the circle.
                   if (I_pos>img(i+1,j-3)&&...
                           I_pos>img(i-1,j-3)&&...
                           I_pos>img(i-2,j-2)&&...
                           I_pos>img(i-3,j-1)&&...
                           I_pos>img(i-3,j+1)&&...
                           I_pos>img(i-2,j+2)&&...
                           I_pos>img(i-1,j+3)&&...
                           I_pos>img(i+1,j+3))||...
                           (I_neg<img(i+1,j-3)&&...
                           I_neg<img(i-1,j-3)&&...
                           I_neg<img(i-2,j-2)&&...
                           I_neg<img(i-3,j-1)&&...
                           I_neg<img(i-3,j+1)&&...
                           I_neg<img(i-2,j+2)&&...
                           I_neg<img(i-1,j+3)&&...
                           I_neg<img(i+1,j+3))
                       corners(i,j) = 1;
                   end
               end
           end
       end
    end
end

[corner_y, corner_x] = find(corners);
corner = [corner_y corner_x];
end
